In [1]:
import torch
import numpy as np
import os
import cv2
import kornia
import matplotlib.pyplot as plt
from models.convlstm import warp_frame_depth
from tools.evaluation_utils import eval_depth

In [2]:
def read_pred_depth(filepath):
    pred_depth = np.load(filepath).astype(np.float32)
    pred_depth /= 1000.
    return pred_depth

def read_gt_depth(filepath):
    # Read depth image and camera pose
    gt_depth = cv2.imread(filepath, -1).astype(np.float32)
    gt_depth = cv2.resize(gt_depth, (256, 192), cv2.INTER_NEAREST)
    gt_depth /= 1000.  # depth is saved in 16-bit PNG in millimeters
    return gt_depth

In [104]:
idx = 180
scan = "scene0628_01"
old_pred_path = f"F:/D/ScanNetv1/scans/{scan}/sr_pred_depth/{idx}_pred_depth.npy"
pred_path = f"F:/P/ML/Project/simplerecon/OUTPUT_PATH/HERO_MODEL/scannetv1/default/viz/quick_viz/{scan}/{idx}_pred_depth.npy"
gt_path = f"F:/D/ScanNetv1/scans/{scan}/depth/{idx}.png"
old_pred_depth = read_pred_depth(old_pred_path)
pred_depth = read_pred_depth(pred_path)
gt_depth = read_gt_depth(gt_path)

print(eval_depth(old_pred_depth, gt_depth))
print(eval_depth(pred_depth, gt_depth))

{'AbsRel': 0.0983399, 'AbsDiff': 0.056413088, 'SqRel': 0.11467976, 'RMSE': 0.20478077, 'LogRMSE': 0.22377816, 'r5': 0.9451116873663619, 'r10': 0.9533915654428825, 'r1': 0.963445703107229, 'r2': 0.9757062917974615, 'r3': 0.9793457986442837, 'complete': 1.0}
{'AbsRel': 0.279728, 'AbsDiff': 0.32170552, 'SqRel': 0.23043087, 'RMSE': 0.4442668, 'LogRMSE': 0.34905425, 'r5': 0.22139575087575633, 'r10': 0.42441199217506026, 'r1': 0.6453300577771712, 'r2': 0.8784632182339293, 'r3': 0.9380146490150585, 'complete': 1.0}


In [96]:
mask = gt_depth > 0.25
old_pred_depth[mask]

array([2.069, 2.074, 2.078, ..., 1.523, 1.522, 1.522], dtype=float32)

In [97]:
pred_depth[mask]

array([2.072, 2.076, 2.08 , ..., 1.524, 1.523, 1.522], dtype=float32)

In [98]:
gt_depth[mask]

array([0.5093125, 0.511125 , 0.5145   , ..., 1.52325  , 1.5248125,
       1.5255625], dtype=float32)

In [100]:
mask.sum()

43869